### PR TITLE
add lab04 (fixed username)

### PR DESCRIPTION
**Pull request by dx2186**

### CODE REVIEW

**Review by azpoliak — APPROVED** [review]
Lgtm

**Comment by azpoliak** [comment]
This merge broke the CI. Before making a pr, please build the site locally to make sure it works

**Comment by dx2186** [comment]
I'm not sure why getting this issue. My local machine cannot get jekyll working. Could you make this post? Thank you so much.

**Comment by azpoliak** [comment]
done

**Pull request merged**
